/**
 * Model: aiMetadataModel.js
 * Lead Engineer: Member 2 & Member 3
 * Description: Data Access Object for ai_metadata, agent_checklists, and weekly_insights.
 */

const db = require('../config/db');

/**
 * Save or update AI metadata for a ticket.
 */
async function saveAIMetadata({
  ticketId,
  customerMood,
  moodConfidence,
  patienceScore,
  predictedResolutionTime,
  overallConfidence,
  timelineSummary = null,
  relatedTicketIds = []
}) {
  const sql = `
    INSERT INTO ai_metadata (
      ticket_id, customer_mood, mood_confidence, patience_score, 
      predicted_resolution_time, overall_confidence, timeline_summary, related_ticket_ids
    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
    ON CONFLICT (ticket_id) DO UPDATE SET
      customer_mood = EXCLUDED.customer_mood,
      mood_confidence = EXCLUDED.mood_confidence,
      patience_score = EXCLUDED.patience_score,
      predicted_resolution_time = EXCLUDED.predicted_resolution_time,
      overall_confidence = EXCLUDED.overall_confidence,
      timeline_summary = COALESCE(EXCLUDED.timeline_summary, ai_metadata.timeline_summary),
      analyzed_at = CURRENT_TIMESTAMP
    RETURNING *;
  `;
  const values = [
    ticketId, customerMood, moodConfidence, patienceScore, 
    predictedResolutionTime, overallConfidence, timelineSummary, JSON.stringify(relatedTicketIds)
  ];
  const result = await db.query(sql, values);
  return result.rows[0];
}

/**
 * Bulk insert agent assist checklist items generated by AI.
 */
async function saveAgentChecklist(ticketId, itemsArray) {
  if (!itemsArray || itemsArray.length === 0) return [];

  // Delete old checklist if re-generated
  await db.query('DELETE FROM agent_checklists WHERE ticket_id = $1', [ticketId]);

  const inserted = [];
  for (const itemText of itemsArray) {
    const res = await db.query(
      'INSERT INTO agent_checklists (ticket_id, item_text, is_completed) VALUES ($1, $2, false) RETURNING *',
      [ticketId, itemText]
    );
    inserted.push(res.rows[0]);
  }
  return inserted;
}

/**
 * Update timeline summary when a ticket is reopened or updated.
 */
async function updateTimelineSummary(ticketId, timelineSummary) {
  const sql = `
    UPDATE ai_metadata
    SET timeline_summary = $1, analyzed_at = CURRENT_TIMESTAMP
    WHERE ticket_id = $2
    RETURNING *;
  `;
  const result = await db.query(sql, [timelineSummary, ticketId]);
  return result.rows[0];
}

/**
 * Fetch latest weekly insights.
 */
async function getLatestWeeklyInsights() {
  const result = await db.query('SELECT * FROM weekly_insights ORDER BY generated_at DESC LIMIT 1;');
  return result.rows[0] || null;
}

module.exports = {
  saveAIMetadata,
  saveAgentChecklist,
  updateTimelineSummary,
  getLatestWeeklyInsights
};
